{% set name = "kedro" %}
{% set version = "0.18.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-{{ version }}.tar.gz
  sha256: 515e163d47234cf22dc116bdc724ea89dee6e92a5d01189b6b94dcdf38b0d9c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.framework.cli:main

requirements:
  host:
    - pip
    - python >=3.7,<3.11
  run:
    - anyconfig >=0.10.0,<0.11.0
    - attrs >=21.3
    - cachetools >=4.1,<6.0
    - click <9.0
    - cookiecutter >=2.1.1,<3.0
    - dynaconf >=3.1.2, <4.0
    - fsspec >=2021.4,<2022.11.1
    - gitpython >=3.0,<4.0
    - importlib_metadata >=3.6
    - importlib_resources >=1.3
    - jmespath >=0.9.5,<1.0
    - jupyter_client >=5.1,<7.0
    - more-itertools >8.14.0,<=9.0
    - omegaconf >=2.1.1, <=2.3
    - pip-tools >=6.6
    - pluggy >=1.0,<1.1
    - python >=3.7,<3.11
    - python-json-logger >=2.0.0,<3.0.0
    - pyyaml >=4.2,<7.0
    - rich >=12.0,<13.0
    - rope >=1.4.0
    - setuptools >=38.0
    - toml >=0.10,<0.11
    - toposort >=1.5,<2.0

test:
  imports:
    - kedro
  commands:
    - kedro --help
# Disabled pip check because of pip-tools and rope
# pip requirements.txt is has requirement pip-tools~=6.10, but conda has only pip-tools 6.6.2
# pip requirements.txt is has requirement rope~=1.5.1, but conda has only rope 1.4.0.
#    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: A Python framework for creating reproducible, maintainable and modular data science code.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - yetudada
    - idanov
    - merelcht
    - antonymilne
    - AhdraMeraliQB
    - jmholzer
    - NeroOkwa
    - noklam
    - SajidAlamQB
